apiVersion: apps/v1
kind: Deployment
metadata:
  name: ittools
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ittools
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ittools
        lbtype: external
    spec:
      containers:
        - name: ittools
          image: ghcr.io/corentinth/it-tools:latest
          ports:
            - name: ittools
              containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
#---
# kind: Service
# apiVersion: v1
# metadata:
#   name: ittools
# spec:
#   selector:
#     app.kubernetes.io/name: ittools
#   type: ClusterIP
#   ports:
#     - name: http
#      port: 1337
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    monitoring.service: ittools
  name: ittools
spec:
  ports:
    - name: ittools
      port: 1400
      targetPort: ittools
  selector:
    app.kubernetes.io/name: ittools
status:
  loadBalancer: {}